version: "3.9"
services:
  database:
    image: postgres:9.6.2-alpine
    container_name: pigp_database
    # network_mode: host
    command: postgres -c listen_addresses='*'
    ports:
      - "${POSTGRESQL_DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB_NAME}
      POSTGRES_USER: ${POSTGRESQL_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_DB_PASSWD}
    volumes:
      - "./data/database/postgres-data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRESQL_DB_NAME}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s  
  app:
    build:
      context: "./"
      args:
        build_env: prod
    # network_mode: host
    container_name: app
    ports:
      - "80:5000"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - "./.env"